version: 1

chains:
  nois:
    chain_id: nois-testnet-000
    prefix: nois
    gas_price: 1unois
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'wasm.nois17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgsve244d' 
    #estimated_block_time: 7000,
    #estimated_indexer_time: 250,
    faucet: http://5rh6rhqad1cgvei7qc96ia3n74.ingress.bigtractorplotting.com:80
    rpc:
      - http://6553qqb75pb27eg2ff5lqvrpso.ingress.akash.pro:80 
  TEMPLATE_RELAYER_CHAIN_NAME:
    chain_id: TEMPLATE_CHAIN_ID
    prefix: TEMPLATE_CHAIN_PREFIX
    gas_price: 0.025TEMPLATE_CHAIN_DENOM
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'wasm.TEMPLATE_NOIS_PROXY_CONTRACT_ADDRESS' #junod query wasm contract  $NOIS_PROXY_CONTRACT_ADDRESS    --node=$NODE_URL
    faucet: TEMPLATE_CHAIN_FAUCET_URL
    rpc:
      - TEMPLATE_CHAIN_NODE_URL