[package]
name = "drand-common"
version = "0.15.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.4.0", features = ["iterator", "ibc3"] }

[dev-dependencies]
