[package]
name = "misc"
version = "0.10.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.2.1", features = ["ibc3"] }
nois.workspace = true
hex = { version = "0.4" }
bech32 = "0.9.1"

[dev-dependencies]
